name: KingOfTheHill
version: '${version}'
main: me.eyetealer.mckingofthehill.kingofthehill.KingOfTheHill
api-version: 1.19

#commands:
#  koth:
#    description: King of the hill command
#    aliases: kingofthehill